// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2-iTqiM_KSuMmBAqFsFgz29V0VTUapk4',
    appId: '1:215561197737:web:d52f42c21609bbdad271b8',
    messagingSenderId: '215561197737',
    projectId: 'materialmanagerment-myhome',
    authDomain: 'materialmanagerment-myhome.firebaseapp.com',
    storageBucket: 'materialmanagerment-myhome.firebasestorage.app',
    measurementId: 'G-8PJTH1BV1N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQyPPAAeQzBIhiXiny3MHCCnvf22NiZFo',
    appId: '1:215561197737:android:72673b1c9f933a2ad271b8',
    messagingSenderId: '215561197737',
    projectId: 'materialmanagerment-myhome',
    storageBucket: 'materialmanagerment-myhome.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2NA4kt2V2WbGsRE-OpuwJvAA-9UHNmw8',
    appId: '1:215561197737:ios:17de0cd6d81166f8d271b8',
    messagingSenderId: '215561197737',
    projectId: 'materialmanagerment-myhome',
    storageBucket: 'materialmanagerment-myhome.firebasestorage.app',
    iosBundleId: 'com.example.materialManagerMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2NA4kt2V2WbGsRE-OpuwJvAA-9UHNmw8',
    appId: '1:215561197737:ios:17de0cd6d81166f8d271b8',
    messagingSenderId: '215561197737',
    projectId: 'materialmanagerment-myhome',
    storageBucket: 'materialmanagerment-myhome.firebasestorage.app',
    iosBundleId: 'com.example.materialManagerMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2-iTqiM_KSuMmBAqFsFgz29V0VTUapk4',
    appId: '1:215561197737:web:fd15fd455f2b64a3d271b8',
    messagingSenderId: '215561197737',
    projectId: 'materialmanagerment-myhome',
    authDomain: 'materialmanagerment-myhome.firebaseapp.com',
    storageBucket: 'materialmanagerment-myhome.firebasestorage.app',
    measurementId: 'G-7JSR56QBTQ',
  );
}
